### PR TITLE
Fix installation on msys2/mingw

### LINKED ISSUE #136: Currently broken for Windows with MSYS2
Installing a version of node (specifically 10.23.2) has the following problems:

- OS detection doesn't work.  
This is because `nvm.fish` line 42 uses `string lower`, but line 52 compares to uppercase strings.
- Solving the above, `curl` (line 81) fails with `curl: (23) Failure writing output to destination`  
I worked around that by having `curl` save to a temp file, and then `tar` read from that file.
- Working around the above, the `tar` part of installing (line 82) fails for some reason I couldn't determine.  
It works if I separate it into two commands instead of using `&&` or `; and` in lines 81-82.
- Working around the above, `_nvm_node_info` fails because apparently `npm` is directly inside `version/bin` instead of `node_modules/npm`, so `package.json` isn't in the same directory.

Using it on Windows 10 with MSYS2.  
`curl` version: 7.74.0 (x86_64-pc-msys)
`tar` version: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp

I decided against making a pull request since I only have workarounds for the above and I can't be sure it would work in general, but I can hope this information helps you figure out the problems.

### PR DESCRIPTION
**Pull request by M4RC3L05**
This PR fixes the installation process on msys2/mingw systems.

Closes: #136

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thanks! This looks a bit complicated, so I'll probably wait until I get my new PC to test and merge this.

**Comment by rgaspary** [comment]
Will this be merged in?

**Comment by jorgebucaran** [comment]
Does it work?

**Comment by M4RC3L05** [comment]
> Does it work?

It did at the time i made the PR.
No idea if it works now, since I do not have the same setup that I had when i made the PR, in order to test it (windows + mingw/msys2)

**Pull request closed without merging**
