### PR TITLE
Print active version after "use" command

### PR DESCRIPTION
**Pull request by yohanboniface**
I think it's good to have a feedback when running a command line, and in our case specifically when using keywords like `latest` or `lts`.

### CODE REVIEW

**Comment by ghost** [comment]
Perhaps behind a --verbose flag or fin_verbose config?

I find too much feedback rather annoying. If fin fails, it should tell you so, of course, but as usual in Unix, showing you nothing is how you know everything ran fine.

Let me think about it, perhaps I can figure out another way ;)

**Comment by ghost** [comment]
Ah, one more thing. Please note that, fin is way more opinionated than nave or nvm. While they are great tools that supports a large variety of use cases, I want fin to be more pragmatic, get out of our way and always (try its best to) do what the user really wants.

The CLI is similar to tj/n, which I found easier to learn than nvm, but without all the dangerous things tj/n does like writing to /usr/local/bin (which requires sudo), etc.

**Comment by yohanboniface** [comment]
> showing you nothing is how you know everything ran fine

I can agree when running `fin 5.5.0`, but when running `fin latest` I feel the contract is not fulfilled without specifying which version fin consider the latest (same for other keywords). Thoughts?

**Comment by yohanboniface** [comment]
> Perhaps behind a --verbose flag or fin_verbose config?

I'd prefer the config way, because needing to add `--verbose` on each command would discourage IMHO ;)

**Comment by yohanboniface** [comment]
Added a fin_verbose check :)

**Comment by ghost** [comment]
Thanks! @yohanboniface, introducing a verbose mode would require revisiting most of the source code and update it accordingly, so instead, here is what I came up with:

screen shot 2016-05-14 at 7 34 42 pm

I still need to improve the CLI in the special use case of switching to `latest` or `lts` when it turns out the version is already installed (in the cache) so we don't have a chance to display the humanized URL, as no download is required.

**Pull request closed without merging**
